<?php

/**
 * @file
 *
 * Very simple integration to post stuff to fb and twitter
 */
 
/*Implementaiton of hook_perm
*/

function simpleshare_perm() {
return array('share content', 'administer simpleshare');
}


/**
 * Implements hook_form_alter().
 *
 * Adds a checkbox to node edit and comment forms.  This checkbox lets
 * facebook users know that content may be published to their Wall,
 * and gives them a chance to prevent that.
 */
function simpleshare_form_alter(&$form, $form_state, $form_id) {
  // Add stream publish option.
    if ($form['#id'] == 'node-form') {
      $node = $form['#node'];
      $simpletypes = array_values(variable_get('simpleshare_node_types', array()));  

      if (in_array($node->type, $simpletypes, TRUE)) {
        $form['simpleshare'] = array(
         '#type' => 'fieldset',
         '#title' => 'Share',
         '#description' => 'After submitting this content you will be be given the opportunity to share it on social networks if you check this box',
         '#access' => user_access('share content'),
        );
      
       $form['simpleshare']['ss_share'] = array(
          '#type' => 'checkbox',
         '#title' => 'Share This',
         '#default_value' => FALSE,
      );
    }
  }
}

/**
 * Implementation of hook_theme().
 */
function simpleshare_theme() {
  return array (
    'simpleshare_modal' => array(
      'template' => 'simpleshare-modal',
      'arguments' => array('node' => NULL),
      'file' => 'simpleshare.modal.inc',
    ),
  );
}


/*
* Implementation of hook_nodeapi
* after node creation, if they've checked to post to social networks, give them the forms to do so
*/
function simpleshare_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  if($op == 'insert' || $op == 'update') {   
     if($node->ss_share == 1) {
        $query = array('simpleshare' => 'true');
        drupal_goto($node->path, $query); 
    }
  }
    
  if($op == 'view' && $_GET['simpleshare'] == 'true') {
    drupal_add_js(drupal_get_path('module', 'simpleshare') . '/simpleshare.js');
    drupal_add_css(drupal_get_path('module', 'simpleshare') . '/simpleshare.css');
    print theme('simpleshare_modal', $node);    
  }
  
  if($op == 'view' && $_GET['simpleshare'] == 'success') {
    //close the facebook window
    $output .= '<SCRIPT LANGUAGE="javascript">window.close();</SCRIPT>';
    print $output;
  }
}

/*
  * Implementation of hook_menu
  */
  
function simpleshare_menu () {
  $items['admin/settings/simpleshare'] = array(
    'title' => 'Simpleshare',
    'description' => 'Settings for Simpleshare',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simpleshare_admin_settings'),
    'access arguments' => array('administer simpleshare'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'simpleshare.admin.inc'
  );
  
  return $items;
}

