<?php

/**
 * @file
 *
 * Very simple integration to post stuff to fb and twitter
 */
 
/*Implementaiton of hook_perm
*/

function simpleshare_perm() {
return array('share content', 'administer simpleshare');
}


/**
 * Implements hook_form_alter().
 *
 * Adds a checkbox to node edit and comment forms.  This checkbox lets
 * facebook users know that content may be published to their Wall,
 * and gives them a chance to prevent that.
 */
function simpleshare_form_alter(&$form, $form_state, $form_id) {
  // Add stream publish option.
    if ($form['#id'] == 'node-form') {
      $node = $form['#node'];
      $simpletypes = array_values(variable_get('simpleshare_node_types', array()));  

      if (in_array($node->type, $simpletypes, TRUE)) {
        $form['simpleshare'] = array(
         '#type' => 'fieldset',
         '#title' => 'Share',
         '#description' => 'After submitting this content you will be be given the opportunity to share it on social networks if you check this box',
         '#access' => user_access('share content'),
        );
      
       $form['simpleshare']['ss_share'] = array(
          '#type' => 'checkbox',
         '#title' => 'Share This',
         '#default_value' => FALSE,
      );
    }
  }
}


/*
* Implementation of hook_nodeapi
* after node creation, if they've checked to post to social networks, give them the forms to do so
*/
function simpleshare_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  if($op == 'insert' || $op == 'update') {   
     if($node->ss_share == 1) {
        $query = array('simpleshare' => 'true');
        drupal_goto($node->path, $query); 
    }
  }
    
  if($op == 'view' && $_GET['simpleshare'] == 'true') {
    drupal_add_js(drupal_get_path('module', 'simpleshare') . '/simpleshare.js');
    drupal_add_css(drupal_get_path('module', 'simpleshare') . '/simpleshare.css');
      
    $fb_appid = variable_get('simpleshare_facebook_id', NULL);
    $link = url('node/' . $node->nid, array('absolute' => TRUE));
    $title = $node->title;
    $description = drupal_substr($node->teaser, 140);
    //add logo in here?  let them add their own? When decided add back to fb_query array
    //$picture = NULL'
    $redirect = url('node/' . $node->nid, array('absolute' => TRUE, 'query' =>array('simpleshare' => 'success')));
    
    $output .= '<div id="fade" class="simpleshare hideme"></div>';
    $output .= '<div id="simpleshare-modal" class="simpleshare hideme">';
    $output .= '<h2>Share it!</h2>';
   
   //build the fb path
    if($fb_appid) {
      $fb_path = url('http://www.facebook.com/dialog/feed');
      $fb_query = array('app_id' => $fb_appid, 'link' => $link, 'name' => $title, 'description' => $description, 'redirect_uri' =>$redirect, 'display' => 'popup');
      //output fb link
     $output .= '<div id="simpleshare-fb">';
      $output .= l('Share on Facebook', $fb_path, array('query' =>$fb_query, 'attributes' => array('class' => 'simpleshare-popup')));
      $output .= '</div>';
    }
   
    //build the twitter path
    $twit_path = url('http://twitter.com/share');
    $twit_query = array('url' => $link, 'text' => $title);
    
    //output twitter link
    if($fb_appid) {
      $output .= '<div id="simpleshare-twitter">';
    } else {
      $output .= '<div id="simpleshare-twitter-nofb">';
    }
    $output .= l('Share on Twitter', $twit_path, array('query' =>$twit_query, 'attributes' => array('class' => 'simpleshare-popup')));
    $output .= '</div>';
    $output .= '<div class="clear close-inv-modal closemodal"><input type="button" value="All Done Sharing"></div>';
    $output .= '</div>';
    
    print $output;
    
  }
  
  if($op == 'view' && $_GET['simpleshare'] == 'success') {
    //close the facebook window
    $output .= '<SCRIPT LANGUAGE="javascript">window.close();</SCRIPT>';
    print $output;
  }
}

/*
  * Implementation of hook_menu
  */
  
function simpleshare_menu () {
  $items['admin/settings/simpleshare'] = array(
    'title' => 'Simpleshare',
    'description' => 'Settings for Simpleshare',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simpleshare_admin_settings'),
    'access arguments' => array('administer simpleshare'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'simpleshare.admin.inc'
  );
  
  return $items;
}

