<?php

/**
 * @file
 *
 * Very simple integration to post stuff to fb and twitter
 */

/**
 * Implements hook_form_alter().
 *
 * Adds a checkbox to node edit and comment forms.  This checkbox lets
 * facebook users know that content may be published to their Wall,
 * and gives them a chance to prevent that.
 */
function simpleshare_form_alter(&$form, $form_state, $form_id) {
  // Add stream publish option.
    if ($form['#id'] == 'node-form') {
      // Add checkbox to control feed publish.
      $form['simpleshare'] = array(
        '#type' => 'fieldset',
        '#title' => 'Share',
      );
      
      $form['simpleshare']['ss_fb'] = array(
        '#type' => 'checkbox',
        '#title' => 'Share on Facebook',
        '#default_value' => FALSE,
      );
    $form['simpleshare']['ss_twitter'] = array(
        '#type' => 'checkbox',
        '#title' => 'Share on Twitter',
        '#default_value' => FALSE,
      );
   
    }
    
}


/*
* Implementation of hook_nodeapi
* after node creation, if they've checked to post to social networks, give them the forms to do so
*/
function simpleshare_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  if($op == 'insert' || $op == 'update') {
    $loaded_node = node_load($node->nid);
     
     if($node->ss_fb == 1) {
      $fb_appid = '140132722716254';
      $link = url($loaded_node->path, array('absolute' => TRUE));
      $title = $loaded_node->title;
      $message= 'Just posted ' . filter_xss($loaded_node->teaser);
      $caption = filter_xss($loaded_node->teaser);
      $picture = 'http://mustardseed.dyndns.tv/screencast/sites/all/themes/acquia_marina/logo.png';
      $redirect =  url($loaded_node->path, array('absolute' => TRUE));
      
      $path = url('http://www.facebook.com/dialog/feed');
      $query = array('app_id' => $fb_appid, 'link' => $link, 'picture' => $picture, 'name' => $title, 'caption' => $caption, 'message' => $message, 'redirect_uri' =>$redirect);
    
      drupal_goto($path, $query, $fragment);
      
      
    }
    
    if($node->ss_twitter == 1) {
      $url = url('node/' . $loaded_node->nid, array('absolute' => TRUE));
      $text = $loaded_node->title;
      
      $path = url('http://twitter.com/share');
      $query = array('url' => $url, 'text' => $text); 
      drupal_goto($path, $query, $fragment);
    }

  }

}




